### ISSUE TITLE
Adding blocks to child themes

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/alps-wordpress-child#1]
I've been trying to add a block to a child theme but haven't had any luck. I've been trying a similar code to what is in the core but trimmed down to just include the new block. Here is what I've tried: 

```
// Only allow the following blocks in Gutenberg
add_filter('allowed_block_types', function () {
  return [
    'core/columns'
  ];
});
```
So far, this hasn't worked. Any hints at what might work?

**Comment by designerbrent** [comment]
This is fixed in version `1.4.2`.

**Comment by davideleuterius** [comment]
@designerbrent I am going to look at this to see what's going on with this.

**Comment by davideleuterius** [comment]
@designerbrent @kelscahill 
I've done some research into this and have the following to share:

This issue exists because we are invoking Gutenberg blocks through a plugin, but this is the suggested approach for implementing custom Gutenberg blocks from WordPress documentation itself.

However, this approach will not provide for a way to allow or hide blocks from parent or child themes. Because it is a plugin, it is available system wide, regardless of what theme you are running. So any blocks added will show up without regards to parent or child theme, and there is no method for separating the two.

That said, if we create the blocks to be as code modules housed inside the themes instead of the plugin, this would allow us to add / show / hide the blocks as desired between the parent and child themes. This would require a fair amount of reworking to make this happen, but would then provide that level of granular control you're wanting here.

Let me know what you think - and thanks!

**Comment by designerbrent** [comment]
Thanks for taking a look @davideleuterius, though I must confess I'm a little puzzled. With ALPS, we are using a module, `ALPS-Gutenberg-Blocks`, to add our custom blocks. Our theme, `ALPS for Wordpress` then uses the `allowed_block_types` filter to restrict which blocks are visible. 

From your response, I'm a little confused: 

> However, this approach will not provide for a way to allow or hide blocks from parent or child themes. Because it is a plugin, it is available system wide, regardless of what theme you are running. So any blocks added will show up without regards to parent or child theme, and there is no method for separating the two.

You say we can't `allow or hide blocks` from the theme, but in my understanding, we are doing just that.

Am I missing something on that?

I certainly don't want to redevelop our blocks, and the hassle of this is getting to be a pain 🙄 to add things explicitly, so I am hoping we can do it via the child theme.

**Comment by davideleuterius** [comment]
@designerbrent 
 Going at this angle (trying to override set blocks in the child), I can't seem to gain any traction on this at all. There is also a real lack of anything anywhere showing how one might explicitly allow what blocks are shown at the child theme level. I think once it is set in the parent theme, that may be the only opportunity you get to set those. I'm still looking into this to see if there is a way to override this.

EDIT: this is the closest I have come to getting some information:
https://wordpress.stackexchange.com/questions/326959/gutenberg-disallow-certain-custom-blocks-but-keep-all-core-blocks

EDIT EDIT: we may be able to do this through javascript. I'm researching that now.

**Comment by davideleuterius** [comment]
@designerbrent 
Good news: I have had a measure of success. It seems we can explicitly load the ALPS Gutenberg blocks. I can't seem to get rid of the core blocks, as I was trying to see if I could do a complete wipe of them and then add back only exactly what we wanted. But this method is actually working. We have a blocks.js file in /dist/scripts that is being enqueued by the child's functions.php file. You can then set the allowed blocks at the top of the blocks.js file. I'll be pushing this code following this message.

**Comment by designerbrent** [comment]
Nice. So maybe I should also be more clear: I don't intend that the child would be blocking any of the blocks the core/parent set. What I want to do on the child is _**ADD**_ blocks that a specific site might want.

This `blocks.js` method seems like it would do that.

**Comment by designerbrent** [comment]
Looking at the `.js` file you have, I don't see any blocks there at aren't in the core theme. Are you able to get it working to call the `core/columns` block?

**Comment by davideleuterius** [comment]
@designerbrent 
If we're just adding new blocks, maybe it might be easiest to have a secondary plugin just for the child theme? Or will these be so specialized per installation that it would rule that out? 

If we're able to just have a child theme plugin, that would be way easier and we wouldn't have to worry about modifying anything coming from the parent.

**Comment by designerbrent** [comment]
The way I see it working would be that when a dev wants an extra block, they would go customize the child theme and use that. I don’t intend to tie the child theme to an update process. They download it, install it, and then customize it instead of the parent. 

So adding another plugin wouldn’t work as well because I don’t have a specific plugin that would go on all child themes. 

- Brent

**Comment by davideleuterius** [comment]
@designerbrent 
Ok - got it. So we need to allow for new custom blocks for the child theme, but do not rely on a supplied plugin to provide them. It will be up to the child theme developer to create the block and tie it in, but we need to be sure that it is possible for them to do so.

Does this sound right?

**Comment by designerbrent** [comment]
Yes. That sounds correct. 

- Brent

**Comment by davideleuterius** [comment]
@designerbrent 
After working with this we can definitely allow child theme users to add their own blocks. However, we have to make a modification to the parent theme. In the parent theme we're specifically white-listing Gutenberg blocks at around line 420 in functions.php, where we are calling all of the blocks we want for the theme. However calling it this way allows ONLY these to be available once this has been called. There is no way to modify this that I have been able to find.

However, we can simply remove the explicit call to allow these ( just delete the whole add_filter call for allowed_block_types ) and they will still load as needed, and then we can also load additional blocks. I tested this by removing that add_filter call in the parent, and then installed a plugin called Atomic Blocks which provides several new Gutenberg blocks. This proved successful - I was able to see the ALPS block along with the Atomic Blocks coming in from the plugin. This should work for any other custom Gutenberg blocks a developer might add.

**Comment by designerbrent** [comment]
@davideleuterius 
So we have the following options: 

1. Explicitly allow certain blocks (_current process_) and those are done in the parent theme, but no other blocks will be allowed. 
2. Remove any filtering on blocks and let anything happen with no control at the parent or child level.

Is that correct?

**Comment by davideleuterius** [comment]
@designerbrent 
Sorry for my delayed response. Yes, that is exactly your options for this unfortunately. It seems you can only allow blocks ONCE, and that then prevents them from being set from a child at that point.

**Comment by designerbrent** [comment]
I'll be closing this as it appears that right now this won't work for child themes.
